Closes #61 "Route summary reporting error"
gis-ops/valhalla-app pull request #111
Opened 2023-03-09 08:29 UTC by rakeshhotker

## 🛠️ Fixes Issue
"Route summary reporting error"

Closes #61

## 👨‍💻 Changes proposed
 
1) Created a helperfunctions.js  file in utils folder
2) In the helperfunctions.js file created the formatDuration function which can be imported for use anywhere required
3) Importing the formatDuration function in Summary.jsx and Map.jsx to make sure the time displayed is same. Hence fixing the issue

## 📄 Note to reviewers
Please let me know of any modifications required.

## 📷 Screenshots
![image](https://user-images.githubusercontent.com/55056403/223964106-3f991280-349c-4aac-a4e9-aa7665e4e371.png)

2023-03-09 09:57 UTC, rakeshhotker commented
Sure, I'll do the necessary changes, thanks for your inputs.

2023-03-10 18:29 UTC, nilsnolde commented on src/utils/durationFormatter.js
> +// }
no comments pls

2023-03-10 18:30 UTC, nilsnolde requested changes
thanks. can you change the filename to `date_time.js`? I'd like to avoid file-sprawl where each tiny function gets its own file.

2023-03-12 17:31 UTC, nilsnolde commented
Jep ok thanks

2023-03-12 17:31 UTC, merged