Closes (#121)
gis-ops/valhalla-app pull request #135
Opened 2023-03-17 13:08 UTC by sandstone991

## 🛠️ Fixes Issue
Debounce Isochrone API calls  #121 

## 👨‍💻 Changes proposed

Changed the UNSAFE_ComponentWillUpdate lifecycle which was ran on every change to see if the sliders values had changed to send a new request, made the component call a debounced fetch function on change instead.
As for the sliders they make request only on the mouseUp event (user let go of the slider).

## 📄 Note to reviewers

I encounted two bugs (unrelated to the task) while working on this component.

- The max value of the range is set to 120 
![image](https://user-images.githubusercontent.com/61756360/225910352-adc7fd4c-b214-4410-8d10-7f752728fbb1.png)
which gives error code 151 when calling Valhalla's API (Exceeded max time 100) so I'm guessing the max value has to change to 100 here

- Some requests return 504 which shows the user this messege 
![image](https://user-images.githubusercontent.com/61756360/225912238-7bf88e37-5b41-45cf-a7c4-360cf8f57ad3.png)
which is unhelpful IMO

I'm also dissatisfied with how async calls are done within this component, given unfortuante enough cirumstances a race condition like this can happen 
![image](https://user-images.githubusercontent.com/61756360/225913267-382842bb-e22b-4d76-9ef9-dda9aeb1739e.png)

but I think that have to wait until the components are rewritten into functional components

Also please consider this a pre-gsoc pr

2023-03-17 14:42 UTC, sandstone991 commented
@nilsnolde kindly review this

2023-03-21 09:34 UTC, chrstnbwnkl requested changes
Just some minor comments

2023-03-21 09:34 UTC, chrstnbwnkl commented on src/Controls/Isochrones/Waypoints/index.jsx
> -                onKeyPress={(event: React.KeyboardEvent) => {
thanks for catching this, shouldn't have made it into master in the first place

2023-03-21 09:34 UTC, chrstnbwnkl commented on src/Controls/Isochrones/Waypoints/index.jsx
> +  // componentDidUpdate(nextProps) {
don't just uncomment unused code, remove it instead

2023-03-21 09:34 UTC, chrstnbwnkl commented on src/Controls/Isochrones/Waypoints/index.jsx
> +// import * as R from 'ramda'
should be removed as well

2023-03-21 09:38 UTC, sandstone991 commented on src/Controls/Isochrones/Waypoints/index.jsx
> +  // componentDidUpdate(nextProps) {
sure, no problem

2023-03-21 09:43 UTC, merged