Height-graph width reduced
gis-ops/valhalla-app pull request #149
Opened 2023-03-24 07:27 UTC by MihirKp25

## 🛠️ Fixes Issue
Closes #136 

## 👨‍💻 Changes proposed

I have reduced the width of height graph from 0.9 to 0.75 in Map.jsx file. I tried to change this width dynamically but it didn't end well. But still it looks pretty nice to me and now we can easily see y axis of height graph.

## 📄 Note to reviewers

If you find a way of reducing the width dynamically whenever the direction tab closes please tell me :)

## 📷 Screenshots
![image9](https://user-images.githubusercontent.com/106189515/227452935-ab9e24e9-33df-494c-b36c-6c087e99a0b5.png)

2023-03-24 08:04 UTC, chrstnbwnkl commented
@MihirKp25 could you please resolve existing conflicts so we can have a look at your PR?

2023-03-24 09:56 UTC, MihirKp25 commented
I have resolved conflicts. Sorry for inconvenience.

2023-03-24 13:28 UTC, nilsnolde requested changes
The whitespace-only changes seem irrelevant, I’d actually expect prettier to complain.. Can you revert those?

2023-03-27 08:09 UTC, chrstnbwnkl requested changes

2023-03-27 08:09 UTC, chrstnbwnkl commented on src/Controls/Directions/Waypoints/Waypoint.jsx
> -
please check your PR again for unnecessary, whitespace-only changes.

2023-03-27 09:49 UTC, MihirKp25 commented on src/Controls/Directions/Waypoints/Waypoint.jsx
> -
Sorry I misinterpreted the last change request and added spaces in this file. I removed those changes. Please let me know if there are any other unnecessary changes I have made. And sorry for the inconvenience.

2023-03-27 11:05 UTC, nilsnolde approved these changes
Fine for me, thanks. I'll let @chrstnbwnkl merge if he's ok with this.

2023-03-27 14:12 UTC, MihirKp25 commented
I will try to make your suggested changes asap.

2023-03-29 07:06 UTC, chrstnbwnkl commented
@MihirKp25 can you push your latest changes? The functionality in the video looks pretty close to what we want to achieve, right?

2023-03-29 07:36 UTC, MihirKp25 commented
Changes are pushed @chrstnbwnkl

2023-03-31 06:16 UTC, nilsnolde commented
This looks pretty good, thanks @MihirKp25 ! 

You can find more info on the proposal here: https://wiki.openstreetmap.org/wiki/Google_Summer_of_Code/2023 and here: https://github.com/gis-ops/valhalla-app/issues/67. If you follow those guidelines you should be good. We have (un)fortunately too many applicants to do extensive proposal review. I suggest you upload it to GSoC, we'll surely read and consider it.

2023-03-31 06:17 UTC, nilsnolde approved these changes

2023-04-07 18:16 UTC, merged