ci: deploying via scp-ssh
gis-ops/valhalla-app pull request #179
Opened 2023-04-08 16:09 UTC by Ananya2001-an

## 🛠️ Fixes Issue
closes #128 

## 👨‍💻 Changes proposed
Automated deployment on every push to master branch.

## 📷 Screenshots
![image](https://user-images.githubusercontent.com/55504616/230731355-2c876a09-e865-44a9-83a7-db9c89bed59c.png)

2023-04-08 17:01 UTC, nilsnolde reviewed
Thanks @Ananya2001-an! Maybe we can remove some of those secrets, IMHO some aren't necessary. I'll create a bot user on the server and a SSH key and put it in the repo's secrets.

2023-04-08 17:01 UTC, nilsnolde commented on .github/workflows/deploy.yml
> +      - master
we'll also want to ignore all paths which are irrelevant for deployments, i.e. most things except `./src` & `/public`

2023-04-08 17:01 UTC, nilsnolde commented on .github/workflows/deploy.yml
> +          key: ${{ secrets.SSH_PRIVATE_KEY }}
it's fine to have the username in clear text

2023-04-08 17:01 UTC, nilsnolde commented on .github/workflows/deploy.yml
> +          host: ${{ secrets.HOST_IP }}
host can also be in the open

2023-04-08 17:01 UTC, nilsnolde commented on .github/workflows/deploy.yml
> +          target: "${{ secrets.HOST_TARGET_DIR }}"
also not a secret IMO

2023-04-08 17:01 UTC, nilsnolde commented on .github/workflows/deploy.yml
> +        uses: appleboy/scp-action@master
Let's try it for now. Usually I prefer to spell out the one command instead of using an (often maintained) custom action. I'd still use a release instead of `master`.

2023-04-08 17:13 UTC, Ananya2001-an commented on .github/workflows/deploy.yml
> +      - master
Yes you are right we have to ignore other files during build job.

2023-04-08 17:15 UTC, Ananya2001-an commented on .github/workflows/deploy.yml
> +          key: ${{ secrets.SSH_PRIVATE_KEY }}
Except the passphrase and secret key we can have other values set as variables instead. Also I hope you understand the need of passphrase. Without it the secret key was not possible to read.

2023-04-08 17:15 UTC, Ananya2001-an commented on .github/workflows/deploy.yml
> +          host: ${{ secrets.HOST_IP }}
Yup we can add it as variable as well.

2023-04-08 17:15 UTC, Ananya2001-an commented on .github/workflows/deploy.yml
> +          target: "${{ secrets.HOST_TARGET_DIR }}"
same

2023-04-08 17:19 UTC, Ananya2001-an commented on .github/workflows/deploy.yml
> +        uses: appleboy/scp-action@master
I too didn't want to use a third party action but actually there are many problems with running commands like `ssh` or `scp` directly in workflow. It wasn;t able to access the keys or gave some terminal error... if you find some solution to it (since I am not good with bash script) then that would be great. For now we can keep it like this.

2023-04-08 19:05 UTC, nilsnolde commented on .github/workflows/deploy.yml
> +        uses: appleboy/scp-action@master
It’s cool for now, no worries. Shouldn’t ever fail, we’ll handroll it:)

2023-04-08 19:05 UTC, nilsnolde commented on .github/workflows/deploy.yml
> +          key: ${{ secrets.SSH_PRIVATE_KEY }}
Sure passphrase is good

2023-04-09 06:13 UTC, Ananya2001-an commented
Changed other secrets to variables and also added necessary paths for deployment.

2023-04-09 06:57 UTC, Ananya2001-an commented
Also we would need to change the homepage url to `https://valhalla.openstreetmap.de/` in package.json, right?

2023-04-09 08:05 UTC, Ananya2001-an commented
I think there is one issue with branch in url like right now in my fork the homepage is set to `https://valhalla-app-tests.gis-ops.com/test` and the page is able to load properly there but when I made a directions request it's giving an error like this: 


https://user-images.githubusercontent.com/55504616/230761517-609c5875-169d-44c4-859f-d9bfdc2cab8b.mp4

Maybe it's happening as we are changing the url path due to permalink function being called. Wdyt?

2023-04-09 15:31 UTC, nilsnolde requested changes
A few more questions:)

2023-04-09 15:31 UTC, nilsnolde commented on .github/workflows/deploy.yml
> +      - 'public/**'
We'll need to add more than those, e.g. package.json (and actually package-lock.json, see #180 ), plus a few more. Anything that's related to deployment needs to trigger a deployment.

Feel free to commit the missing package-lock.json in this PR.

2023-04-09 15:31 UTC, nilsnolde commented on .github/workflows/deploy.yml
> +          strip_components: 1
What does this do?

2023-04-09 15:31 UTC, nilsnolde commented on .github/workflows/deploy.yml
> +          overwrite: true
Is `overwrite` enough? Won't that leave all the previous build artifacts on the server? I.e. all the JS chunks that it compiles have a hash in their file name. I might be wrong but I don't think we'd remove them like this..

Can you have a look if the action can remove the target path before it copies the build folder?

2023-04-09 15:37 UTC, nilsnolde commented
> Also we would need to change the homepage url to https://valhalla.openstreetmap.de/ in package.json, right?

Yep, I mentioned that in the chat I think.

https://valhalla-app-tests.gis-ops.com/test/ show "HACKED" on the title. Was that you? 

When I request for directions, it works just fine, but it changes URL to https://valhalla-app-tests.gis-ops.com/ (i.e. without `/test`).

> due to permalink function being called

Maybe, I don't remember the code that well. But that should still resolve to the base URL which is with `/test`. I don't understand why it switches to the other URL. Can you have test around a bit to see what's going on?

2023-04-09 15:43 UTC, nilsnolde commented
In any case, we can get to the PR deployments in the next PR with a new GHA workflow.

2023-04-09 15:47 UTC, Ananya2001-an commented on .github/workflows/deploy.yml
> +      - 'public/**'
Sure I will do this 👍🏼

2023-04-09 15:49 UTC, Ananya2001-an commented on .github/workflows/deploy.yml
> +          strip_components: 1
Without this it would create a build folder with the contents inside it.

2023-04-09 15:55 UTC, Ananya2001-an commented
> Yep, I mentioned that in the chat I think. You can add that in this PR as well. 

 Sure

> https://valhalla-app-tests.gis-ops.com/test/ shows "HACKED" on the title. Was that you?

yup 😆 don't worry 

> When I request for directions, it works just fine, but it changes URL to https://valhalla-app-tests.gis-ops.com/ (i.e. without `/test`). Your video also doesn't show any error. What's in the console?

`TypeError: Cannot read properties of undefined (reading 'type')
    at t.componentDidUpdate (index.jsx:137:7)
 `
This is the error in console.

> > due to permalink function being called
> 
> Maybe, I don't remember the code that well. But that should still resolve to the base URL which is with `/test`. I don't understand why it switches to the other URL. Can you have test around a bit to see what's going on?

Yeah I will see to it. It shouldn't remove the `test` path IMO but lets see what's the prob.

2023-04-09 15:57 UTC, Ananya2001-an commented
> In any case, we can get to the PR deployments in the next PR with a new GHA workflow.

Yeah the PR deployments will be a separate workflow. We need to resolve issues with the url path first of all otherwise PR deployments wont work as well.

2023-04-09 16:01 UTC, Ananya2001-an commented on .github/workflows/deploy.yml
> +          overwrite: true
I think it is overwriting the existing files. There were no previous artifacts left. Still I will dig into this a bit more.

2023-04-10 09:16 UTC, nilsnolde requested changes
- need to include files `.env` and `js-config.json`
- `rm: true` for the action

2023-04-10 09:29 UTC, Ananya2001-an commented
If we are keeping `rm: true` I don't think we need overwrite anymore so I will remove it too.

2023-04-10 10:01 UTC, Ananya2001-an commented
Made the final changes after testing things on my fork. The `rm` option is working well. 

Also I tried changing the permalink function to see if that error gets removed and it's working. So I will make changes to the permalink function for the PR deployment later. You can check yourself: https://valhalla-app-tests.gis-ops.com/test

2023-04-10 10:48 UTC, nilsnolde commented
Sweet thanks!

2023-04-10 10:49 UTC, merged

2023-04-10 10:49 UTC, nilsnolde commented
let's see if this worked then:)

2023-04-10 10:50 UTC, Ananya2001-an commented
> let's see if this worked then:)

Yeah hope it does :)

2023-04-10 10:54 UTC, nilsnolde commented on package.json
>    "name": "converter-demo-app",
we should also rename this eventually. it's pretty irrelevant, but still:)

2023-04-10 10:55 UTC, Ananya2001-an commented on package.json
>    "name": "converter-demo-app",
yeah sure

2023-04-10 10:56 UTC, Ananya2001-an commented
The deploy failed...I don't think there's any issue with the keys. Is the target path right?

2023-04-10 11:07 UTC, nilsnolde commented
https://github.com/appleboy/scp-action/issues/106

Exactly the reason why I'm wary of third-party actions :smile: wouldn't have expected it to never even work though.

I suggest you dig into how to do that with bash. We'll have to do that for the PR workflow anyways. Couple of hints:
- here we do smth similar for the FOSSGIS website: https://github.com/fossgis/fossgis-webseite/blob/4043661b4ee320e8e16b1b02ced550653b86dcca/.github/workflows/main.yml#L34
- to test, don't use github actions. try it first from your own linux. once that works, you can try actions. the only additional step needed should be registering the private key with the github server's ssh client, like in the linked step above

2023-04-10 11:25 UTC, Ananya2001-an commented
I guess you are right...we would have to do this with bash only. But I still don't understand why this happened since it worked on the fork till now. I saw that there's something wrong with the version but still weird....anyways I will follow what u said. I too had a bad feeling about using third party actions. Also I will disable the workflow for now else it will start running on future merges :)

2023-04-10 12:41 UTC, appleboy commented
@Ananya2001-an @nilsnolde Please try v0.1.3 version. `appleboy/scp-action@v0.1.3` I will take a look at the v0.1.4 version.