motorcycle profile for direction (copy from car)
gis-ops/valhalla-app pull request #196
Opened 2023-09-22 09:41 UTC by nvcnvn

## 👨‍💻 Changes proposed

Adding motorcycle profile (for now just copy everything from auto)

## 📄 Note to reviewers

I don't have a proper motorcycle icon, so I reuse bike icon

## 📷 Screenshots
![Screenshot 2023-09-22 at 16 40 39](https://github.com/gis-ops/valhalla-app/assets/1708320/06e7835e-59c7-488d-a471-9004582d458b)

2023-09-22 21:02 UTC, nilsnolde requested changes
Copying (mostly) from auto should be fine, but we'd want
- at least `use_trails`: https://valhalla.github.io/valhalla/api/turn-by-turn/api-reference/#motorcycle-costing-options-beta
- definitely a motorcycle SVG

before merging.

2023-09-25 09:09 UTC, nilsnolde requested changes
Just one more minor thing, then it's good to merge.

2023-09-25 09:09 UTC, nilsnolde commented on src/Controls/settings-options.js
> +  use_trails: 1,
the default needs to be 0 as per docs

2023-09-25 10:31 UTC, nvcnvn commented on src/Controls/settings-options.js
> +  use_trails: 1,
ooppps, not sure why I missed that.

2023-09-25 11:28 UTC, nilsnolde commented
pity the PR workflow is broken, would love to see it before merging. not sure what's wrong there. seems the secret is not really taken by actions. I just re-pasted it but  still nothing.. smth must've changed in how secrets are referred to.

anyways, thanks for the changes @nvcnvn , looks safe to me to deploy regardless.

2023-09-25 11:28 UTC, merged