add date-time option for easy testing conditional-turn-restriction
gis-ops/valhalla-app pull request #200
Opened 2023-10-25 08:39 UTC by nvcnvn

## 👨‍💻 Changes proposed
- Add date-time picker (for easier testing time-based turn restriction)

## 📷 Screenshots
![Screenshot 2023-10-25 at 15 37 01](https://github.com/gis-ops/valhalla-app/assets/1708320/3d088fd9-7631-4c24-8fdd-6659ec507a12)

2023-10-25 13:05 UTC, nilsnolde commented
Thanks, that'd be a nice addition which would make the app much more useful. A couple of comments:
- seems like it's now mandatory to give a date/time? Would be better if it was opt-in, e.g. the default item in the dropdown could be "Anytime" or so and a greyed out date/time field. WDYT?
- the `moment` library causes a build failure: https://github.com/gis-ops/valhalla-app/actions/runs/6637880358/job/18036721164?pr=200. Can you have a look?

2023-10-25 14:29 UTC, nvcnvn commented
> * seems like it's now mandatory to give a date/time? Would be better if it was opt-in, e.g. the default item in the dropdown could be "Anytime" or so and a greyed out date/time field. WDYT?

I just want to clarify the behavior of Valhalla in this case, should "Anytime" (empty date_time)  different with "Current" (date_time.type = 0)?
Because most of the time we: A don't care about time, B want to test departure/arrival.

2023-10-25 14:33 UTC, nilsnolde commented
Yes it will be different. If you say datetime.type = 0, then it’ll use the current time, ie time will be respected (incl restrictions, but also traffic if it’s loaded). When you don’t want to respect time, then you don’t send the date_time object in the request at all. And I agree, the latter will be the vast majority of requests.

2023-10-30 17:22 UTC, chrstnbwnkl requested changes
Thanks @nvcnvn , just a couple of comments!

2023-10-30 17:22 UTC, chrstnbwnkl commented on src/components/datetime-picker.jsx
> +import React from 'react'
File name should be pascal case

2023-10-30 17:22 UTC, chrstnbwnkl commented on src/components/datetime-picker.jsx
> +        marginLeft="3px"
redundant

2023-10-30 17:22 UTC, chrstnbwnkl commented on src/components/datetime-picker.jsx
> +        marginLeft: 'auto',
doesn't seem to have any effect

2023-10-30 17:22 UTC, chrstnbwnkl commented on src/actions/directionsActions.js
> +  const { profile, date_time } = getState().common
no snake_case please, use camelCase

2023-10-30 17:22 UTC, chrstnbwnkl commented on src/reducers/common.js
> +    value: moment().format('yyyy-MM-DDTHH:mm'),
Not sure why we have to use moment.js here, it's been in maintenance mode for a while. I think `new Date(Date.now()).toISOString().slice(0, 19)` should do the trick

2023-10-30 17:22 UTC, chrstnbwnkl commented on src/Controls/Directions/index.jsx
> +    const { profile, loading, date_time } = this.props
again, please use camelCase

2023-11-16 05:15 UTC, nvcnvn commented
> Thanks @nvcnvn , just a couple of comments!

Finally I found some time to update the PR.

2023-12-15 09:32 UTC, chrstnbwnkl requested changes
Sorry for not getting back to this earlier... Looks like you forgot to check in the renamed datepicker component file?

2023-12-29 08:08 UTC, nvcnvn commented
> Sorry for not getting back to this earlier... Looks like you forgot to check in the renamed datepicker component file?

ah you are right

2024-01-30 14:25 UTC, chrstnbwnkl approved these changes
...and again sorry for the long wait. LGTM!

2024-01-30 14:26 UTC, merged