fixed issue #53
gis-ops/valhalla-app pull request #64
Opened 2023-02-22 13:13 UTC by Ghat0tkach

fixes the issue of  sidebar content extend vertically all the way , changed the default px to vh for better height across all devices

2023-02-23 10:35 UTC, nilsnolde commented
See https://github.com/gis-ops/valhalla-app/issues/67 . We can open it again once we get to this point.

2023-02-27 08:07 UTC, nilsnolde commented
We can open this one now again, after we have our guidelines: https://github.com/gis-ops/valhalla-app/wiki/GSoC-2023.

2023-02-27 09:23 UTC, nilsnolde commented
Please revert the last update, see https://github.com/gis-ops/valhalla-app/pull/66. Also, point 3 in our guidelines: https://github.com/gis-ops/valhalla-app/wiki/GSoC-2023#the-process.

2023-02-27 09:24 UTC, nilsnolde commented
We'll let you know if we think you should tackle another issue. Another way to show your interest is doing some OSM mapping. It's surely a good addition to your project proposal.

2023-02-27 09:26 UTC, Ghat0tkach commented
actually you assigned the issue #63 to me ,thats why i pulled this request . no worries i'll revert the updates
and thank you for the suggestions

2023-02-27 09:31 UTC, nilsnolde commented
Oh damn, I'm sorry! Jep, my bad! Thanks for your understanding!

2023-03-02 11:51 UTC, nilsnolde approved these changes

2023-03-04 15:05 UTC, nilsnolde requested changes

2023-03-04 15:05 UTC, nilsnolde commented on src/components/CustomSlider.jsx
> + // console.log(sliderVal)
Naa, please remove it entirely

2023-03-04 15:18 UTC, nilsnolde commented on src/Controls/Directions/Waypoints/index.jsx
> +  height: 65 + 'vh',
I wonder: instead of using the entire available vertical height, could it be enough to just change the z-index of the geocoding result list so it's appearing on top of its parent component?

2023-03-04 15:18 UTC, nilsnolde commented on src/Controls/Directions/Waypoints/index.jsx
> +  height: 65 + 'vh',
It's a bit weird now, tons of empty space

2023-03-04 15:19 UTC, nilsnolde commented on src/components/CustomSlider.jsx
> +
and the line.. please run the app before pushing, prettier will throw here

2023-03-04 16:19 UTC, Ghat0tkach commented on src/components/CustomSlider.jsx
> +
oh yes , i did using z-index , is it fine?
![image](https://user-images.githubusercontent.com/59855919/222916963-12c797a8-f117-4e20-bd4f-b1488b68c8ef.png)

2023-03-04 16:19 UTC, Ghat0tkach commented on src/Controls/Directions/Waypoints/index.jsx
> +  height: 65 + 'vh',
i did using z-index is it , fine?
![image](https://user-images.githubusercontent.com/59855919/222917008-6062cc3c-f50d-41b3-89a7-2584549c648c.png)

2023-03-04 16:26 UTC, nilsnolde commented on src/Controls/Directions/Waypoints/index.jsx
> +  height: 65 + 'vh',
for me yes. we can merge like this and if @chrstnbwnkl wants to have it all the way to the bottom (like you did before), he can do it then. thanks

2023-03-04 17:27 UTC, Ghat0tkach commented
i was re-requesting review from @nilsnolde  and while i did so , it automatically removed request from @chrstnbwnkl

2023-03-06 09:21 UTC, nilsnolde approved these changes

2023-03-06 09:21 UTC, nilsnolde commented
Thanks!

2023-03-06 09:22 UTC, merged

2023-03-06 12:17 UTC, Ghat0tkach commented
Really had  a lot of fun in exploring the codebase . Thank you for giving me the opportunity.