Route summary reporting error fixed
gis-ops/valhalla-app pull request #69
Opened 2023-02-27 09:48 UTC by rakeshhotker

As told, i reverted to the Route summary reporting error so as to focus on one bug.

2023-03-04 15:24 UTC, nilsnolde requested changes

2023-03-04 15:24 UTC, nilsnolde commented on src/Controls/Directions/Summary.jsx
> +    return days + hours + minutes
not DRY, please outsource and re-use

2023-03-06 09:24 UTC, nilsnolde commented on src/Controls/Directions/Summary.jsx
> +    return days + hours + minutes
although, now there's #91 , so likely the other place where this is done, will change to a hh:mm:ss format. maybe we should do that here too?

2023-03-06 11:37 UTC, nilsnolde commented on src/Controls/Directions/Summary.jsx
> +    return days + hours + minutes
ended up not using hh:mm:ss format, but compress it a bit regardless in #94.  we should re-use that function.

2023-03-06 11:43 UTC, rakeshhotker commented
Could you please be more descriptive

2023-03-06 11:53 UTC, nilsnolde commented
You copy/pasted this function as-is from another place in the same codebase. You're repeating the same stuff, that's never good.

Did you look at #94? You'll need to merge master, then you can apply your changes while having the function live somewhere else and called by both modules.

2023-03-08 19:35 UTC, aaryahjolia commented
Can I make a PR on this @nilsnolde ? I solved this issue by DRY principle and in hh:mm:ss format.

2023-03-09 07:43 UTC, nilsnolde commented
Depends if @rakeshhotker is dropping the contribution or not, I'd still give him some time.

2023-03-09 08:33 UTC, closed without merging