gh#45: UX enhancements when a user enters a value out of valid range
gis-ops/valhalla-app pull request #70
Opened 2023-02-27 18:17 UTC by theWiseAman

### Pull Request Description
* Issues: #45 
* Fix Description: 
  * Input value when goes out of range is clamped at the extremes of the range

2023-02-27 18:24 UTC, theWiseAman commented
@nilsnolde Will this do? This way we won't need to display any warnings when a user inputs any large or too-small number which is not within the `min` and `max` range.

2023-02-27 18:47 UTC, nilsnolde commented
This is be helpful too. And should be fine for now.

Actually it was about the `warnings` array in the Valhalla response. It's best to have client- & server-side checks. But more generally, Valhalla can respond with warnings which doesn't have anything to do with wrong input, e.g. a second pass for the routing or whatever, the user has no influence on that. So what we'd like is that there's a toast or so that pops up and presents the user with all warnings that were generated by Valhalla. See https://valhalla.github.io/valhalla/api/turn-by-turn/api-reference/#outputs-of-a-route. 

It does depend a bit on an open PR I have since ages: https://github.com/valhalla/valhalla/pull/3833. So, that should be done first, otherwise it'll be hard(er) for you to test. All warnings which are currently generated can't be triggered by the web app.

2023-02-27 18:48 UTC, nilsnolde commented
All those open issues were more for us. And we have the full context since we're also maintaining the routing project. I really need to go through these and add more context!

2023-02-27 19:32 UTC, theWiseAman commented
@nilsnolde I think then you could merge this PR. I could check this issue again once the API is fully complete I suppose?

2023-02-27 19:58 UTC, nilsnolde commented on src/components/CustomSlider.jsx
> +    // console.log("Before: value", value)
no comments..

2023-02-27 19:58 UTC, nilsnolde commented on src/components/CustomSlider.jsx
> +    }
`value` can't be below `min` AND above `max`

2023-02-27 20:44 UTC, theWiseAman commented on src/components/CustomSlider.jsx
> +    }
@nilsnolde Do you want something like this?
```javascript
if (value < min && value < max) {
    value = min
} else if (value > max && value > min) {
    value = max
}
```

2023-02-27 20:56 UTC, nilsnolde commented on src/components/CustomSlider.jsx
> +    }
this is enough:
```suggestion
    if (value < min) {
      value = min
    } else if (value > max) {
      value = max
    }
```

just doesn't make sense to check twice

2023-02-27 21:18 UTC, theWiseAman commented on src/components/CustomSlider.jsx
> +    }
@nilsnolde ok that's what I thought initially.

2023-03-02 11:53 UTC, nilsnolde approved these changes

2023-03-04 15:48 UTC, nilsnolde requested changes
I can't see it working, can you? If I input 5000 for cycling speed, it stays 5000.

2023-03-04 15:50 UTC, theWiseAman commented
Let me check once again

2023-03-04 15:53 UTC, theWiseAman commented
@nilsnolde I have committed my changes in a different branch. Are you sure you are in the correct branch?

2023-03-04 16:22 UTC, theWiseAman commented
@nilsnolde I have checked it on my remote machine. It's working fine. Should I merge it to master branch? I hadn't merged it in master branch earlier to avoid any conflicts.

2023-03-04 16:29 UTC, nilsnolde commented
Yes, you're right, sorry, must've done smth wrong earlier. Though I'm not going through the ordeal of pulling from all your remotes, I use the patch files from Github: https://patch-diff.githubusercontent.com/raw/gis-ops/valhalla-app/pull/70.patch. It's a quick & easy way to review in IDE IMO. Probably I was on the wrong patch, currently going through all PRs.

2023-03-04 16:30 UTC, merged